name: build-qt6-windows_x86_64_mingw_gcc_martrix

on:
  workflow_dispatch:
    inputs:
      qt_version:
        description: 'QT Version'
        required: true
        default: '6.9.1'
      gcc_version:
        description: 'GCC Version'
        required: true
        default: '15.1.0'
      runtime:
        description: 'Runtime (ucrt/msvcrt)'
        required: true
        default: 'ucrt'
        type: choice
        options:
        - ucrt
        - msvcrt
      create_release:
        description: 'Create Release'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

env:
  QT_VERSION: ${{ github.event.inputs.qt_version || '6.9.1' }}
  GCC_VERSION: ${{ github.event.inputs.gcc_version || '15.1.0' }}
  RUNTIME: ${{ github.event.inputs.runtime || 'ucrt' }}

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        link_type: [static, shared]
        build_type: [release, debug, release-sepdbg]
        exclude:
          - link_type: static
            build_type: debug
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: Extract Qt major.minor version
        id: qt_version
        run: |
          $version = "${{ env.QT_VERSION }}"
          $parts = $version.Split('.')
          $major_minor = "$($parts[0]).$($parts[1])"
          echo "major_minor=$major_minor" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Get MinGW release info
        id: mingw_release
        run: |
          try {
            $gccVersion = "${{ env.GCC_VERSION }}"
            $runtime = "${{ env.RUNTIME }}"
            
            # 获取所有 releases
            $releasesUrl = "https://api.github.com/repos/niXman/mingw-builds-binaries/releases"
            $releases = Invoke-RestMethod -Uri $releasesUrl -Headers @{ "User-Agent" = "GitHub-Actions" }
            
            # 查找匹配的 GCC 版本
            $targetRelease = $null
            foreach ($release in $releases) {
              if ($release.tag_name -like "$gccVersion-rt_v*") {
                $targetRelease = $release
                break
              }
            }
            
            if ($targetRelease) {
              # 提取 rt 和 rev 信息
              $tagName = $targetRelease.tag_name
              if ($tagName -match "$gccVersion-rt_(v\d+)-(rev\d+)") {
                $rt = $matches[1]
                $rev = $matches[2]
                
                # 查找对应的资源文件
                $assetName = "x86_64-$gccVersion-release-posix-seh-$runtime-rt_$rt-$rev.7z"
                $asset = $targetRelease.assets | Where-Object { $_.name -eq $assetName }
                
                if ($asset) {
                  echo "download_url=$($asset.browser_download_url)" >> $env:GITHUB_OUTPUT
                  echo "file_name=$assetName" >> $env:GITHUB_OUTPUT
                  echo "rt_version=$rt" >> $env:GITHUB_OUTPUT
                  echo "revision=$rev" >> $env:GITHUB_OUTPUT
                  echo "found=true" >> $env:GITHUB_OUTPUT
                  Write-Host "Found release: $tagName"
                  Write-Host "Asset: $assetName"
                  Write-Host "URL: $($asset.browser_download_url)"
                } else {
                  echo "found=false" >> $env:GITHUB_OUTPUT
                  Write-Host "Asset not found: $assetName"
                }
              } else {
                echo "found=false" >> $env:GITHUB_OUTPUT
                Write-Host "Could not parse tag name: $tagName"
              }
            } else {
              echo "found=false" >> $env:GITHUB_OUTPUT
              Write-Host "No release found for GCC $gccVersion"
            }
          } catch {
            Write-Host "Error: $_"
            echo "found=false" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Setup MinGW64
        run: |
          cd ..
          
          if ("${{ steps.mingw_release.outputs.found }}" -eq "true") {
            # 使用动态获取的信息
            $downloadUrl = "${{ steps.mingw_release.outputs.download_url }}"
            $fileName = "${{ steps.mingw_release.outputs.file_name }}"
            Write-Host "Downloading from API result: $downloadUrl"
            curl -L -o $fileName $downloadUrl
          } else {
            # 后备方案：使用静态映射表
            $gccVersion = "${{ env.GCC_VERSION }}"
            $runtime = "${{ env.RUNTIME }}"
            $versionMap = @{
              "15.1.0" = @{ rt = "rt_v12"; rev = "rev0" }
              "14.2.0" = @{ rt = "rt_v12"; rev = "rev2" }
              "14.1.0" = @{ rt = "rt_v12"; rev = "rev0" }
              "13.2.0" = @{ rt = "rt_v11"; rev = "rev1" }
              "13.1.0" = @{ rt = "rt_v11"; rev = "rev1" }
              "12.2.0" = @{ rt = "rt_v10"; rev = "rev2" }
            }
            
            if ($versionMap.ContainsKey($gccVersion)) {
              $rt = $versionMap[$gccVersion].rt
              $rev = $versionMap[$gccVersion].rev
            } else {
              $rt = "rt_v12"
              $rev = "rev0"
            }
            
            $fileName = "x86_64-$gccVersion-release-posix-seh-$runtime-$rt-$rev.7z"
            $downloadUrl = "https://github.com/niXman/mingw-builds-binaries/releases/download/$gccVersion-$rt-$rev/$fileName"
            
            Write-Host "Downloading from fallback: $downloadUrl"
            curl -L -o $fileName $downloadUrl
          }
          
          7z x $fileName
        shell: pwsh

      - name: Setup Ninja
        run: |
          cd ..
          mkdir ninja
          curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip
          unzip -q ninja.zip -d ./ninja

      - name: Setup Protobuf (for QtGRPC)
        run: |
          cd ..
          curl -L -o protoc-win64.zip https://github.com/protocolbuffers/protobuf/releases/download/v30.2/protoc-30.2-win64.zip
          unzip -q protoc-win64.zip -d ./protoc
          echo "D:\a\QtBuild\protoc\bin" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Prepare directories and source
        run: |
          cd ..
          mkdir Qt
          cd Qt
          mkdir "${{ env.QT_VERSION }}"
          mkdir "${{ env.QT_VERSION }}-${{ matrix.link_type }}"
          curl -L -o qt-everywhere-src.zip "https://download.qt.io/official_releases/qt/${{ steps.qt_version.outputs.major_minor }}/${{ env.QT_VERSION }}/single/qt-everywhere-src-${{ env.QT_VERSION }}.zip"
          unzip -q qt-everywhere-src.zip -d "./${{ env.QT_VERSION }}"

      - name: Run build script
        shell: cmd
        run: |
          setlocal enableextensions enabledelayedexpansion

          set QT_VERSION=${{ env.QT_VERSION }}
          set GCC_VERSION=${{ env.GCC_VERSION }}
          set BUILD_TYPE=${{ matrix.build_type }}
          set LINK_TYPE=${{ matrix.link_type }}
          set RUNTIME=${{ env.RUNTIME }}

          if "%BUILD_TYPE%"=="release-sepdbg" (
            set BUILD_TYPE=release
            if "%LINK_TYPE%"=="shared" (
              set SEPARATE_DEBUG=true
            ) else (
              set SEPARATE_DEBUG=false
            )
          ) else if "%BUILD_TYPE%"=="debug" (
            set BUILD_TYPE=debug
            set SEPARATE_DEBUG=false
          ) else (
            set SEPARATE_DEBUG=false
          )

          call D:\a\QtBuild\QtBuild\Qt6Build\build-qt6-windows_x86_64_mingw_gcc.cmd !QT_VERSION! !GCC_VERSION! !BUILD_TYPE! !LINK_TYPE! !SEPARATE_DEBUG! !RUNTIME!

      - name: Package binaries
        run: |
          $linkType = "${{ matrix.link_type }}"
          $buildType = "${{ matrix.build_type }}"
          $qtVersion = "${{ env.QT_VERSION }}"
          $gccVersion = "${{ env.GCC_VERSION }}"
          $runtime = "${{ env.RUNTIME }}".ToLower()
          
          # 规范化构建类型名称 (小写)
          $buildTypeNormalized = switch ($buildType) {
            "release" { "release" }
            "debug" { "debug" }
            "release-sepdbg" { "relwithdebinfo" }
            default { $buildType.ToLower() }
          }
          
          # 规范化链接类型名称 (小写)
          $linkTypeNormalized = switch ($linkType) {
            "static" { "static" }
            "shared" { "shared" }
            default { $linkType.ToLower() }
          }
          
          # 修正后的命名格式：qt版本-windows-x86_64-mingw_gcc版本-链接类型_构建类型
          $archiveName = "qt${qtVersion}-windows-x86_64-mingw_gcc${gccVersion}_${runtime}-${linkTypeNormalized}_${buildTypeNormalized}.7z"
          $sourcePath = "D:\a\QtBuild\Qt\$qtVersion-$linkType"
          
          # 检查源目录是否存在
          if (Test-Path $sourcePath) {
            # 创建临时目录用于重组目录结构
            $tempDir = "D:\a\QtBuild\temp_package"
            $finalDirName = "qt${qtVersion}-windows-x86_64-mingw_gcc${gccVersion}_${runtime}-${linkTypeNormalized}_${buildTypeNormalized}"
            $finalPath = Join-Path $tempDir $finalDirName
            
            # 清理并创建临时目录
            if (Test-Path $tempDir) {
              Remove-Item $tempDir -Recurse -Force
            }
            New-Item -ItemType Directory -Path $finalPath -Force | Out-Null
            
            # 获取编译器目录（mingw15.1.0_64_UCRT格式）
            $compilerDirs = Get-ChildItem -Path $sourcePath -Directory | Where-Object { $_.Name -like "mingw*" }
            if ($compilerDirs.Count -eq 0) {
              Write-Host "Error: No mingw compiler directory found in $sourcePath"
              Get-ChildItem -Path $sourcePath
              exit 1
            }
            
            $compilerDir = $compilerDirs[0].FullName
            Write-Host "Found compiler directory: $compilerDir"
            
            # 复制编译器目录下的所有内容到最终目录
            Copy-Item -Path "$compilerDir\*" -Destination $finalPath -Recurse -Force
            
            # 创建压缩包
            Set-Location $tempDir
            7z a "..\$archiveName" $finalDirName -mx=9
            
            echo "Archive created: $archiveName"
            echo "Source path: $compilerDir"
            echo "Final structure: $finalDirName"
            
            # 验证压缩包内容
            7z l "..\$archiveName" | Select-Object -First 20
            
            # 输出到环境变量供后续步骤使用
            echo "ARCHIVE_NAME=$archiveName" >> $env:GITHUB_ENV
            
            # 清理临时目录
            Set-Location "D:\a\QtBuild"
            Remove-Item $tempDir -Recurse -Force
          } else {
            echo "Error: Source path does not exist: $sourcePath"
            exit 1
          }
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: qt${{ env.QT_VERSION }}-windows-x86_64-mingw_gcc${{ env.GCC_VERSION }}_${{ env.RUNTIME }}-${{ matrix.link_type }}_${{ matrix.build_type == 'release' && 'release' || matrix.build_type == 'debug' && 'debug' || 'relwithdebinfo' }}
          path: ${{ env.ARCHIVE_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_release == 'true' }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate release tag
        id: release_tag
        run: |
          TAG_NAME="qt${{ env.QT_VERSION }}-windows-mingw${{ env.GCC_VERSION }}-${{ env.RUNTIME }}-$(date +'%Y%m%d%H%M%S')"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Tag name: $TAG_NAME"

      - name: Generate release notes
        id: release_notes
        run: |
          cat << EOF > release_notes.md
          # Qt ${{ env.QT_VERSION }} Windows MinGW Build
          
          ## Build Information
          - **Qt Version**: ${{ env.QT_VERSION }}
          - **Compiler**: MinGW GCC ${{ env.GCC_VERSION }}
          - **Runtime**: ${{ env.RUNTIME }}
          - **Build Date**: $(date +'%Y-%m-%d %H:%M:%S UTC')
          - **Build Runner**: GitHub Actions (windows-latest)
          
          ## Included Configurations
          This release includes the following build configurations:
          
          ### Static Builds
          - \`static_release\`: Static linking, Release mode
          - \`static_relwithdebinfo\`: Static linking, Release mode with separate debug info (if supported)
          
          ### Shared Builds
          - \`shared_release\`: Dynamic linking, Release mode
          - \`shared_debug\`: Dynamic linking, Debug mode
          - \`shared_relwithdebinfo\`: Dynamic linking, Release mode with separate debug info
          
          ## File Naming Convention
          Files follow the pattern: \`qt{version}-windows-x86_64-mingw_gcc{gcc_version}_{runtime}-{link_type}_{build_type}.7z\`
          
          Where:
          - \`{version}\`: Qt version (e.g., 6.9.1)
          - \`{gcc_version}\`: GCC version (e.g., 15.1.0)
          - \`{runtime}\`: Runtime library (ucrt or msvcrt)
          - \`{link_type}\`: static or shared
          - \`{build_type}\`: release, debug, or relwithdebinfo
          
          ## Installation
          1. Download the appropriate .7z file for your needs
          2. Extract using 7-Zip or compatible software
          3. The Qt installation will be in the extracted folder with bin, lib, qml, etc. directories
          
          ## Notes
          - Static builds do not include debug configurations
          - Shared builds include MinGW runtime DLLs
          - All builds skip QtWebEngine and examples/tests
          - Built with C++20 standard
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_tag.outputs.tag_name }}
          name: Qt ${{ env.QT_VERSION }} - MinGW ${{ env.GCC_VERSION }} (${{ env.RUNTIME }})
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: artifacts/**/*.7z
          fail_on_unmatched_files: true
          generate_release_notes: false

      - name: Clean up artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: qt${{ env.QT_VERSION }}-windows-x86_64-mingw_gcc${{ env.GCC_VERSION }}_${{ env.RUNTIME }}-*