name: Build_Qt5.15.17_x86_64-windows-mingw_gcc8.1_shared

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 5.15.17
  QT_VERSION2: 5.15
  FILE_NAME: shared-Release_mingw810_64

jobs:
  windows_mingw64_shared_release:
    runs-on: windows-2022

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 Perl    
    - name: Setup Perl
      run: |
        cd ..  #Directory: D:\a\QtBuild
        curl -L -o strawberry-perl-64bit-portable.zip https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip
        Expand-Archive -Path strawberry-perl-64bit-portable.zip -DestinationPath ./Strawberry -Force

    # 安装 MinGW810_64    
    - name: Setup MinGW64
      run: |
        cd ..  #Directory: D:\a\QtBuild
        New-Item -ItemType Directory -Force -Path mingw64
        curl -L -o mingw810.7z https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw81/qt.tools.win64_mingw810/8.1.0-1-202411201005x86_64-8.1.0-gdb-11.2.0-release-posix-seh-rt_v6-rev0.7z
        7z x mingw810.7z -oD:\a\QtBuild\mingw64

    # 构建Qt
    - name: Build Qt
      run: |
        # 创建文件夹
        cd ..  #Directory: D:\a\QtBuild
        New-Item -ItemType Directory -Force -Path Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\QtBuild\Qt
        New-Item -ItemType Directory -Force -Path ${{env.QT_VERSION}}
        New-Item -ItemType Directory -Force -Path "${{env.QT_VERSION}}-shared"

        # 下载源代码并解压
        curl -L -o qt-everywhere-opensource-src.zip https://download.qt.io/archive/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-opensource-src-${{env.QT_VERSION}}.zip
        Expand-Archive -Path qt-everywhere-opensource-src.zip -DestinationPath ./${{env.QT_VERSION}} -Force

        # 调用编译脚本
        cmd.exe /c "call `"D:\a\QtBuild\QtBuild\Qt5Build\Build_Qt5.15.17_x86_64-windows-mingw_gcc8.1_shared.cmd`""

    # 打包
    - name: Package binaries
      run: |
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-shared -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z