# =============================================================================
# Qt 6 Linux x86_64 LLVM Build Matrix
# Standardized workflow for building Qt with LLVM/Clang on Linux via WSL2
# =============================================================================

name: build-qt6-native-linux_x86_64_llvm_matrix

on:
  workflow_dispatch:
    inputs:
      qt_version:
        description: 'Qt Version'
        required: true
        default: '6.9.2'
        type: string
      compiler_version:
        description: 'LLVM/Clang Version'
        required: true
        default: '18'
        type: choice
        options:
        - '15'
        - '16'
        - '17'
        - '18'
        - '19'
        - '20'
      vulkan_sdk:
        description: 'Vulkan SDK (none for disable, runtime-* for specific version)'
        required: true
        type: choice
        options:
        - 'none'
        - 'runtime-1.4.321.0'
        - 'runtime-1.3.290.0'
        default: 'none'
      test_mode:
        description: 'Test Mode (build qtbase only for faster testing)'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'
      create_release:
        description: 'Create Release'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

env:
  QT_VERSION: ${{ github.event.inputs.qt_version || '6.9.2' }}
  COMPILER_VERSION: ${{ github.event.inputs.compiler_version || '18' }}
  VULKAN_CHOICE: ${{ github.event.inputs.vulkan_sdk || 'none' }}
  TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
  ACTIONS_STEP_DEBUG: 'true'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        link_type: [static, shared]
        build_type: [release, debug, release-sepdbg]
        exclude:
          - link_type: static
            build_type: debug  # Skip static debug builds for resource efficiency
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup WSL2 with Ubuntu 24.04
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-24.04
          use-cache: 'false'
          set-as-default: 'true'

      - name: Extract Qt major.minor version
        id: qt_version
        run: |
          $version = "${{ env.QT_VERSION }}"
          $parts = $version.Split('.')
          $major_minor = "$($parts[0]).$($parts[1])"
          echo "major_minor=$major_minor" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create scripts with proper line endings
        run: |
          # WSL 设置脚本 - LLVM安装优化以降低内存使用
          $setupScript = "#!/bin/bash`nset -e`necho `"Setting up WSL2 environment with LLVM/Clang...`"`n`nexport DEBIAN_FRONTEND=noninteractive`n`n# 限制apt内存使用`necho 'APT::Cache-Start 12582912;' | sudo tee /etc/apt/apt.conf.d/00cache`necho 'APT::Cache-Grow 1048576;' | sudo tee -a /etc/apt/apt.conf.d/00cache`n`necho `"Adding LLVM APT repository...`"`nwget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc`necho `"deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${{ env.COMPILER_VERSION }} main`" | sudo tee /etc/apt/sources.list.d/llvm.list`n`nsudo apt-get update`n`necho `"Installing LLVM/Clang toolchain...`"`nsudo apt-get install -y --no-install-recommends clang-${{ env.COMPILER_VERSION }} clang++-${{ env.COMPILER_VERSION }} lld-${{ env.COMPILER_VERSION }}`n`necho `"Installing libc++ libraries...`"`nsudo apt-get install -y --no-install-recommends libc++-${{ env.COMPILER_VERSION }}-dev libc++abi-${{ env.COMPILER_VERSION }}-dev`n`necho `"Installing build tools...`"`nsudo apt-get install -y --no-install-recommends cmake ninja-build python3 pkg-config`n`necho `"Installing core X11/OpenGL libraries...`"`nsudo apt-get install -y --no-install-recommends libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxcursor-dev`n`necho `"Installing XCB libraries...`"`nsudo apt-get install -y --no-install-recommends libxcb1-dev libxcb-util-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-randr0-dev libxcb-cursor-dev`n`necho `"Installing remaining dependencies...`"`nsudo apt-get install -y --no-install-recommends libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libfreetype6-dev libglib2.0-dev libegl1-mesa-dev libssl-dev wget curl xz-utils`n`necho `"Setting up alternatives...`"`nsudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ env.COMPILER_VERSION }} 100`nsudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ env.COMPILER_VERSION }} 100`nsudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-${{ env.COMPILER_VERSION }} 100`n`necho `"Verifying installation...`"`nclang-${{ env.COMPILER_VERSION }} --version`nclang++-${{ env.COMPILER_VERSION }} --version`nlld-${{ env.COMPILER_VERSION }} --version`n`nsudo apt-get clean`nsudo rm -rf /var/lib/apt/lists/*`necho `"LLVM environment setup completed`""
          [System.IO.File]::WriteAllText("wsl_setup.sh", $setupScript.Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))

          # 下载脚本
          $downloadScript = "#!/bin/bash`nset -e`nqt_version=`"${{ env.QT_VERSION }}`"`nmajor_minor=`"${{ steps.qt_version.outputs.major_minor }}`"`nsource_url=`"https://download.qt.io/official_releases/qt/`$major_minor/`$qt_version/single/qt-everywhere-src-`$qt_version.tar.xz`"`n`necho `"Downloading Qt source...`"`nwget -O `"qt-everywhere-src-`$qt_version.tar.xz`" `"`$source_url`""
          [System.IO.File]::WriteAllText("download_qt.sh", $downloadScript.Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))

          # 主构建脚本
          $mainBuildScript = "#!/bin/bash`nset -e`n`necho `"Starting Qt Linux build script with LLVM/Clang in WSL2...`"`n`nqt_version=`"`$QT_VERSION`"`ncompiler_version=`"`$COMPILER_VERSION`"`nbuild_type=`"`$BUILD_TYPE`"`nlink_type=`"`$LINK_TYPE`"`nseparate_debug=`"`$SEPARATE_DEBUG`"`nvulkan_choice=`"`$VULKAN_CHOICE`"`ntest_mode=`"`$TEST_MODE`"`n`necho `"=== Build Parameters ===`"`necho `"Qt Version: `$qt_version`"`necho `"LLVM Version: `$compiler_version`"`necho `"Build Type: `$build_type`"`necho `"Link Type: `$link_type`"`necho `"Separate Debug: `$separate_debug`"`necho `"Test Mode: `$test_mode`"`necho `"Vulkan Support: `$vulkan_choice`"`necho `"========================`"`n`necho `"Extracting Qt source...`"`nif [ -f `"qt-everywhere-src-`$qt_version.tar.xz`" ]; then`n    tar -xf qt-everywhere-src-`$qt_version.tar.xz`n    rm qt-everywhere-src-`$qt_version.tar.xz`nelse`n    echo `"Error: Qt source file not found`"`n    exit 1`nfi`n`nSRC_QT=`"`$(pwd)/qt-everywhere-src-`$qt_version`"`nBUILD_DIR=`"`$(pwd)/build`"`nINSTALL_DIR=`"`$(pwd)/install`"`n`nmkdir -p `"`$BUILD_DIR`"`nmkdir -p `"`$INSTALL_DIR`"`ncd `"`$BUILD_DIR`"`n`n# 设置编译器环境变量`nexport CC=clang-`${compiler_version}`nexport CXX=clang++-`${compiler_version}`nexport LLVM_INSTALL_DIR=/usr/lib/llvm-`${compiler_version}`n`n# Configure Qt build options`nCFG_OPTIONS=`"-`$link_type -prefix `$INSTALL_DIR -c++std c++20 -opensource -confirm-license -qt-libpng -qt-libjpeg -qt-zlib -qt-pcre -openssl-linked -platform linux-clang -opengl desktop`"`n`n# Add test mode configuration`nif [ `\"`$test_mode`\" = `\"true`\" ]; then`n  CFG_OPTIONS=`\"`$CFG_OPTIONS -nomake examples -nomake tests -skip qtwebengine -skip qttools -skip qtdoc`\"`n  echo `\"Test mode enabled: building qtbase only`\"`nelse`n  CFG_OPTIONS=`\"`$CFG_OPTIONS -nomake examples -nomake tests -skip qtwebengine`\"`nfi`n`n# Disable Vulkan to avoid compatibility issues`nCFG_OPTIONS=`"`$CFG_OPTIONS -no-feature-vulkan`"`n`n# Build type configuration`nif [ `"`$build_type`" = `"debug`" ]; then`n    CFG_OPTIONS=`"`$CFG_OPTIONS -debug`"`nelse`n    CFG_OPTIONS=`"`$CFG_OPTIONS -release`"`nfi`n`n# Separate debug info for shared builds`nif [ `"`$link_type`" = `"shared`" ] && [ `"`$separate_debug`" = `"true`" ]; then`n    CFG_OPTIONS=`"`$CFG_OPTIONS -force-debug-info -separate-debug-info`"`nfi`n`n# 设置额外的编译器和链接器标志`nexport CFLAGS=`"-fuse-ld=lld`"`nexport CXXFLAGS=`"-fuse-ld=lld -stdlib=libc++`"`nexport LDFLAGS=`"-fuse-ld=lld -stdlib=libc++`"`n`necho `"=== Qt Configuration ===`"`necho `"Configure options: `$CFG_OPTIONS`"`necho `"========================`"`n`necho `"Configuring Qt with Clang/LLVM...`"`necho `"Using CC=`$CC, CXX=`$CXX`"`n`"`$SRC_QT/configure`" `$CFG_OPTIONS`n`necho `"Building Qt...`"`nPARALLEL_JOBS=`$(nproc)`nif [ `$PARALLEL_JOBS -gt 3 ]; then`n    PARALLEL_JOBS=3  # Limit for resource-constrained environments`nfi`n`n# Set memory-optimized compiler flags`nexport CXXFLAGS=`"`$CXXFLAGS -fno-lto`"`nexport LDFLAGS=`"`$LDFLAGS -Wl,--no-keep-memory`"`n`necho `"Using `$PARALLEL_JOBS parallel jobs`"`ncmake --build . --parallel `$PARALLEL_JOBS`n`necho `"Installing Qt...`"`ncmake --install .`n`n# Save build configuration summary`necho `"Searching for config.summary file...`"`nconfig_summary_found=false`n`n# Search in multiple possible locations`nfor search_path in `"`$(pwd)/config.summary`" `"`$(pwd)/../config.summary`" `"`$(pwd)/qtbase/config.summary`" `"`$(find . -name 'config.summary' 2>/dev/null | head -1)`"; do`n  if [ -f `"`$search_path`" ]; then`n    echo `"Found config.summary at: `$search_path`"`n    cp `"`$search_path`" `"`$(pwd)/../build_summary.txt`"`n    echo `"Build summary saved from `$search_path`"`n    config_summary_found=true`n    break`n  fi`ndone`n`n# If no config.summary found, create basic fallback`nif [ `"`$config_summary_found`" = `"false`" ]; then`n  echo `"WARNING: config.summary not found in any expected location`"`n  echo `"Available files in build directory:`"`n  ls -la . || true`n  echo `"Creating basic build summary...`"`n  echo `"Qt `$qt_version Linux LLVM Build Summary`" > `"`$(pwd)/../build_summary.txt`"`n  echo `"=====================================`" >> `"`$(pwd)/../build_summary.txt`"`n  echo `"Build Type: `$build_type`" >> `"`$(pwd)/../build_summary.txt`"`n  echo `"Link Type: `$link_type`" >> `"`$(pwd)/../build_summary.txt`"`n  echo `"Compiler: LLVM/Clang `$compiler_version`" >> `"`$(pwd)/../build_summary.txt`"`n  echo `"Platform: Linux x86_64 (WSL2)`" >> `"`$(pwd)/../build_summary.txt`"`n  echo `"Test Mode: `$test_mode`" >> `"`$(pwd)/../build_summary.txt`"`n  echo `"Build Date: `$(date +'%Y-%m-%d %H:%M:%S UTC')`" >> `"`$(pwd)/../build_summary.txt`"`nfi`n`n# Cleanup source directory`ncd `"`$(pwd)/..`"`nrm -rf `"qt-everywhere-src-`$qt_version`"`n`necho `"=== Qt build completed successfully ===`""
          [System.IO.File]::WriteAllText("build-qt6-native-linux_x86_64_llvm.sh", $mainBuildScript.Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))

          # 构建脚本调用器
          $buildScript = "#!/bin/bash`nset -e`n`nqt_version=`"${{ env.QT_VERSION }}`"`ncompiler_version=`"${{ env.COMPILER_VERSION }}`"`nbuild_type=`"${{ matrix.build_type }}`"`nlink_type=`"${{ matrix.link_type }}`"`nvulkan_choice=`"${{ env.VULKAN_CHOICE }}`"`ntest_mode=`"${{ env.TEST_MODE }}`"`n`nactual_build_type=`"`$build_type`"`nseparate_debug=`"false`"`nif [ `"`$build_type`" = `"release-sepdbg`" ]; then`n  actual_build_type=`"release`"`n  if [ `"`$link_type`" = `"shared`" ]; then`n    separate_debug=`"true`"`n  fi`nfi`n`nexport QT_VERSION=`"`$qt_version`"`nexport COMPILER_VERSION=`"`$compiler_version`"`nexport BUILD_TYPE=`"`$actual_build_type`"`nexport LINK_TYPE=`"`$link_type`"`nexport SEPARATE_DEBUG=`"`$separate_debug`"`nexport VULKAN_CHOICE=`"`$vulkan_choice`"`nexport TEST_MODE=`"`$test_mode`"`n`nchmod +x ./build-qt6-native-linux_x86_64_llvm.sh`n./build-qt6-native-linux_x86_64_llvm.sh"
          [System.IO.File]::WriteAllText("build_qt.sh", $buildScript.Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
        shell: pwsh

      - name: Setup WSL2 environment and dependencies
        run: |
          wsl bash ./wsl_setup.sh

      - name: Setup Vulkan SDK
        if: ${{ env.VULKAN_CHOICE != 'none' }}
        run: |
          $vulkanScript = "#!/bin/bash`necho `"Setting up Vulkan SDK for Linux...`"`n`nchoice=`"${{ env.VULKAN_CHOICE }}`"`nvulkan_root=`"/opt/vulkan_sdk`"`nsudo mkdir -p `"`$vulkan_root`"`n`ncase `"`$choice`" in`n  'runtime-1.4.321.0')`n    sdk_version=`"1.4.321.0`"`n    hdr_tag=`"vulkan-sdk-1.4.321.0`"`n    ;;`n  'runtime-1.3.290.0')`n    sdk_version=`"1.3.290.0`" `n    hdr_tag=`"v1.3.290`"`n    ;;`n  *)`n    echo `"Unsupported Vulkan SDK choice: `$choice`"`n    exit 1`n    ;;`nesac`n`nwork_dir=`"/tmp/vulkan_build`"`nrm -rf `"`$work_dir`"`nmkdir -p `"`$work_dir`"`ncd `"`$work_dir`"`n`n# 安装系统 Vulkan 开发包`nexport DEBIAN_FRONTEND=noninteractive`nsudo apt-get update`nsudo apt-get install -y --no-install-recommends \`n  libvulkan-dev \`n  vulkan-tools \`n  vulkan-utility-libraries-dev \`n  spirv-tools \`n  wget \`n  unzip`n`n# 下载并安装官方 Vulkan SDK (包含额外的工具和头文件)`nsdk_url=`"https://sdk.lunarg.com/sdk/download/`$sdk_version/linux/vulkansdk-linux-x86_64-`$sdk_version.tar.gz`"`necho `"Downloading Vulkan SDK from: `$sdk_url`"`nif wget -q --timeout=60 --tries=3 `"`$sdk_url`" -O vulkan_sdk.tar.gz 2>/dev/null; then`n  if [ -f vulkan_sdk.tar.gz ] && [ `$(stat -c%s vulkan_sdk.tar.gz) -gt 1000000 ]; then`n    echo `"Extracting Vulkan SDK...`"`n    if sudo tar -xzf vulkan_sdk.tar.gz -C `"`$vulkan_root`" --strip-components=1 2>/dev/null; then`n      sudo chown -R root:root `"`$vulkan_root`"`n      echo `"Official Vulkan SDK installed successfully`"`n    else`n      echo `"SDK extraction failed, using system packages only`"`n    fi`n  else`n    echo `"SDK download incomplete, using system packages only`"`n  fi`nelse`n  echo `"SDK download failed, using system packages only`"`nfi`n`n# 确保基本的 SDK 结构存在`nsudo mkdir -p `"`$vulkan_root`"/{include,lib,bin}`n`n# 如果官方SDK安装失败，回退到系统包`nif [ ! -f `"`$vulkan_root/include/vulkan/vulkan.h`" ]; then`n  echo `"Setting up fallback using system packages...`"`n  # 链接系统库`n  sudo ln -sf /usr/include/vulkan `"`$vulkan_root/include/`" 2>/dev/null || true`n  sudo ln -sf /usr/lib/x86_64-linux-gnu/libvulkan.so* `"`$vulkan_root/lib/`" 2>/dev/null || true`n  sudo ln -sf /usr/bin/vulkaninfo `"`$vulkan_root/bin/`" 2>/dev/null || true`nfi`n`n# 下载最新的 Vulkan-Headers (为了确保兼容性)`nhdr_url=`"https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/`$hdr_tag.zip`"`necho `"Downloading Vulkan headers: `$hdr_url`"`nwget -q `"`$hdr_url`" -O vulkan_headers.zip`n`nif [ -f vulkan_headers.zip ] && [ `$(stat -c%s vulkan_headers.zip) -gt 100000 ]; then`n  unzip -q vulkan_headers.zip`n  hdr_dir=`$(find . -maxdepth 1 -type d -name `"Vulkan-Headers-*`" | head -1)`n  if [ -n `"`$hdr_dir`" ] && [ -d `"`$hdr_dir/include/vulkan`" ]; then`n    sudo rm -rf `"`$vulkan_root/include/vulkan`"`n    sudo cp -r `"`$hdr_dir/include/vulkan`" `"`$vulkan_root/include/`"`n    sudo chown -R root:root `"`$vulkan_root/include/vulkan`"`n  fi`nfi`n`n# 设置环境变量文件`necho `"export VULKAN_SDK=`$vulkan_root`" | sudo tee /etc/environment.d/vulkan.conf`necho `"export VK_SDK_PATH=`$vulkan_root`" | sudo tee -a /etc/environment.d/vulkan.conf`necho `"export PATH=`$vulkan_root/bin:`\`$PATH`" | sudo tee -a /etc/environment.d/vulkan.conf`necho `"export LD_LIBRARY_PATH=`$vulkan_root/lib:`\`$LD_LIBRARY_PATH`" | sudo tee -a /etc/environment.d/vulkan.conf`necho `"export VK_LAYER_PATH=`$vulkan_root/etc/vulkan/explicit_layer.d`" | sudo tee -a /etc/environment.d/vulkan.conf`n`n# 验证安装`nif [ -f `"`$vulkan_root/include/vulkan/vulkan.h`" ]; then`n  echo `"Vulkan headers installed successfully`"`nelse`n  echo `"Warning: Vulkan headers not found`"`nfi`n`nif [ -f `"`$vulkan_root/lib/libvulkan.so`" ] || [ -f `"/usr/lib/x86_64-linux-gnu/libvulkan.so.1`" ]; then`n  echo `"Vulkan library found`"`nelse`n  echo `"Warning: Vulkan library not found`"`nfi`n`necho `"Vulkan SDK setup completed`"`necho `"SDK Path: `$vulkan_root`""
          [System.IO.File]::WriteAllText("vulkan_setup.sh", $vulkanScript.Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
          wsl bash ./vulkan_setup.sh

      - name: Download Qt source in WSL2
        run: |
          wsl bash ./download_qt.sh

      - name: Build Qt in WSL2
        run: |
          wsl bash ./build_qt.sh

      - name: Package binaries
        run: |
          $linkType = "${{ matrix.link_type }}"
          $buildType = "${{ matrix.build_type }}"
          $qtVersion = "${{ env.QT_VERSION }}"
          $compilerVersion = "${{ env.COMPILER_VERSION }}"
          
          # Normalize build type name
          $buildTypeNormalized = switch ($buildType) {
            "release" { "release" }
            "debug" { "debug" }
            "release-sepdbg" { "relwithdebinfo" }
            default { $buildType.ToLower() }
          }
          
          # Create standardized archive name
          $archiveName = "qt${qtVersion}-linux-x86_64-llvm${compilerVersion}-${linkType}_${buildTypeNormalized}.tar.xz"
          
          Write-Host "Creating archive: $archiveName"
          wsl tar -cJf $archiveName -C install .
          
          if (Test-Path $archiveName) {
            Write-Host "Archive created successfully: $(Get-Item $archiveName | Select-Object -ExpandProperty Length) bytes"
            echo "ARCHIVE_NAME=$archiveName" >> $env:GITHUB_ENV
          } else {
            Write-Error "Failed to create archive"
            exit 1
          }
          
          # Prepare build report
          $reportName = "qt-build-report_${linkType}_${buildType}.txt"
          if (wsl test -f build_summary.txt) {
            wsl cp build_summary.txt $reportName
          } else {
            $basicReport = "Qt ${{ env.QT_VERSION }} Build Report`n" + 
                          "Build Type: $buildType`n" +
                          "Link Type: $linkType`n" +
                          "Compiler: LLVM/Clang ${{ env.COMPILER_VERSION }}`n" +
                          "Platform: Linux x86_64 (WSL2)`n" +
                          "Build Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
            [System.IO.File]::WriteAllText($reportName, $basicReport, [System.Text.UTF8Encoding]::new($false))
          }
          echo "REPORT_FILE=$reportName" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: qt${{ env.QT_VERSION }}-linux-x86_64-llvm${{ env.COMPILER_VERSION }}-${{ matrix.link_type }}_${{ matrix.build_type == 'release' && 'release' || matrix.build_type == 'debug' && 'debug' || 'relwithdebinfo' }}
          path: ${{ env.ARCHIVE_NAME }}
          if-no-files-found: error

      - name: Upload build report
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.link_type }}_${{ matrix.build_type }}
          path: ${{ env.REPORT_FILE }}
          if-no-files-found: error

      # Note: This workflow only builds and uploads artifacts
      # Use the 'release-qt-unified' workflow to create releases with all platforms