name: Build_Qt6.9.1_x86_64-linux-gnu_gcc14.2_shared

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 6.9.1
  QT_VERSION2: 6.9
  FILE_NAME: shared-Release_gcc14_64
  GCC_VERSION: 14.2.0

jobs:
  ubuntu_gcc14_shared_release:
    runs-on: ubuntu-24.04

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 更新系统并安装依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build curl unzip p7zip-full
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev
        sudo apt-get install -y libxcb1-dev libxcb-util-dev libxcb-image0-dev
        sudo apt-get install -y libxcb-keysyms1-dev libxcb-render-util0-dev
        sudo apt-get install -y libxcb-xinerama0-dev libfontconfig1-dev
        sudo apt-get install -y libfreetype6-dev libx11-dev libx11-xcb-dev
        sudo apt-get install -y libxext-dev libxfixes-dev libxi-dev libxrender-dev
        sudo apt-get install -y libssl-dev libdbus-1-dev libasound2-dev
        sudo apt-get install -y software-properties-common

    # 安装 GCC 14
    - name: Install GCC 14
      run: |
        # 添加 Ubuntu Toolchain PPA
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        
        # 检查可用的 GCC 版本
        echo "Available GCC packages in PPA:"
        apt-cache search gcc- | grep -E "gcc-[0-9]+" | head -10
        
        # 安装 GCC 14
        sudo apt-get install -y gcc-14 g++-14
        
        # 创建兼容性目录和符号链接，模拟原来的路径结构
        sudo mkdir -p /opt/gcc-15.1.0/bin
        sudo ln -sf /usr/bin/gcc-14 /opt/gcc-15.1.0/bin/gcc
        sudo ln -sf /usr/bin/g++-14 /opt/gcc-15.1.0/bin/g++
        
        # 设置默认版本
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 60
        
        # 验证安装
        echo "Installed GCC versions:"
        gcc-14 --version
        g++-14 --version
        gcc --version
        g++ --version
        
        # 验证兼容性路径
        echo "Verifying compatibility paths:"
        /opt/gcc-15.1.0/bin/gcc --version
        /opt/gcc-15.1.0/bin/g++ --version

    # 构建Qt
    - name: Build Qt
      run: |
        # 设置GCC环境变量，确保构建脚本能找到编译器
        export PATH="/opt/gcc-15.1.0/bin:$PATH"
        export CC="/opt/gcc-15.1.0/bin/gcc"
        export CXX="/opt/gcc-15.1.0/bin/g++"
        export LD_LIBRARY_PATH="/usr/lib/gcc/x86_64-linux-gnu/14:$LD_LIBRARY_PATH"
        
        # 创建文件夹
        cd ..  # Directory: /home/runner/work/QtBuild
        mkdir -p Qt

        # 创建文件夹
        cd Qt   # Directory: /home/runner/work/QtBuild/Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-shared

        # 下载源代码并解压
        curl -L -o qt-everywhere-src.tar.xz https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-src-${{env.QT_VERSION}}.tar.xz
        tar -xf qt-everywhere-src.tar.xz -C ./${{env.QT_VERSION}}

        # 删除源码包节省空间
        rm qt-everywhere-src.tar.xz

        # 调用编译脚本
        bash "/home/runner/work/QtBuild/QtBuild/Qt6Build/Build_Qt6.9.1_x86_64-linux-gnu_gcc14.2_shared.sh"

    # 打包
    - name: Package binaries
      run: |
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-shared -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z