name: Build_Qt5.15.17_x86_64-windows-msvc_2022_static

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 5.15.17
  QT_VERSION2: 5.15
  FILE_NAME: static-Release_msvc2022_64

jobs:
  windows_msvc_static_release:
    runs-on: windows-2022

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 Perl    
    - name: Setup Perl
      run: |
        cd ..  #Directory: D:\a\QtBuild
        curl -L -o strawberry-perl-64bit-portable.zip https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip
        Expand-Archive -Path strawberry-perl-64bit-portable.zip -DestinationPath ./Strawberry -Force

    # 安装 jom
    - name: Setup jom
      run: |
        cd ..  #Directory: D:\a\QtBuild
        curl -L -o jom.zip  http://download.qt.io/official_releases/jom/jom.zip
        Expand-Archive -Path jom.zip -DestinationPath ./jom -Force

    # 安装msvc
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # 安装vsdevenv
    - name: Setup vsdevenv
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    # 构建Qt
    - name: Build Qt
      run: |
        # 创建文件夹
        cd ..  #Directory: D:\a\QtBuild
        New-Item -ItemType Directory -Force -Path Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\QtBuild\Qt
        New-Item -ItemType Directory -Force -Path ${{env.QT_VERSION}}
        New-Item -ItemType Directory -Force -Path "${{env.QT_VERSION}}-static"

        # 下载源代码并解压
        curl -L -o qt-everywhere-opensource-src.zip https://download.qt.io/archive/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-opensource-src-${{env.QT_VERSION}}.zip
        Expand-Archive -Path qt-everywhere-opensource-src.zip -DestinationPath ./${{env.QT_VERSION}} -Force

        # 调用编译脚本
        cmd.exe /c "call `"D:\a\QtBuild\QtBuild\Qt5Build\Build_Qt5.15.17_x86_64-windows-msvc_2022_static.cmd`""

    # 打包
    - name: Package binaries
      run: |
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-static -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z