name: Build_Qt6.9.1_wasm32-emscripten3.1.70_gcc15.1

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 6.9.1
  QT_VERSION2: 6.9
  EMSCRIPTEN_VERSION: 3.1.70
  FILE_NAME: static-Release_wasm32_emscripten

jobs:
  windows_wasm_static_release:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 MinGW64 (主要用于工具)
    - name: Setup MinGW64
      run: |
        cd ..  #Directory: D:\a\QtBuild
        curl -L -o x86_64-release-posix-seh-ucrt.7z https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0.7z
        7z x D:\a\QtBuild\x86_64-release-posix-seh-ucrt.7z -oD:\a\QtBuild

    # 安装 Ninja
    - name: Setup Ninja
      run: |
        cd ..  #Directory: D:\a\QtBuild
        mkdir -p ninja
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip
        unzip -q ninja.zip -d ./ninja

    # 安装 Emscripten SDK
    - name: Setup Emscripten
      run: |
        cd ..  #Directory: D:\a\QtBuild
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        .\emsdk.bat install ${{env.EMSCRIPTEN_VERSION}}
        .\emsdk.bat activate ${{env.EMSCRIPTEN_VERSION}}

    # 下载Host Qt
    - name: Download Host Qt
      run: |
        cd ..  #Directory: D:\a\QtBuild
        mkdir -p Qt/${{env.QT_VERSION}}-host
        cd Qt/${{env.QT_VERSION}}-host
        
        # 下载你提供的Host Qt
        curl -L -o host-qt.7z "https://github.com/yuanpeirong/buildQt/releases/download/Qt6.9.1_rev0/Qt_6.9.1-static-Release_mingw1510_64_UCRT.7z"
        7z x host-qt.7z

    # 构建Qt
    - name: Build Qt
      run: |
        # 创建文件夹
        cd ..  #Directory: D:\a\QtBuild
        mkdir -p Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\QtBuild\Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-static

        # 下载源代码并解压，源代码目录D:\a\QtBuild\Qt\${{env.QT_VERSION}}\XXX
        curl -L -o qt-everywhere-src.zip https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-src-${{env.QT_VERSION}}.zip
        unzip -q qt-everywhere-src.zip -d ./${{env.QT_VERSION}}

        # 调用编译脚本
        cmd.exe /c "call `"D:\a\QtBuild\QtBuild\Qt6Build\Build_Qt6.9.1_wasm32-emscripten3.1.70_gcc15.1.cmd`""

    # 打包
    - name: Package binaries
      run: |
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-static -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z