name: Build_Qt6.9.1_wasm32-emscripten3.1.70_gcc15.1

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 6.9.1
  QT_VERSION2: 6.9
  EMSCRIPTEN_VERSION: 3.1.70
  FILE_NAME: static-Release_wasm32_emscripten

jobs:
  windows_wasm_static_release:
    runs-on: windows-latest
    timeout-minutes: 480  # 8小时超时

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 MinGW64 (主要用于工具)
    - name: Setup MinGW64
      run: |
        cd ..  #Directory: D:\a\QtBuild
        curl -L -o x86_64-release-posix-seh-ucrt.7z https://github.com/niXman/mingw-builds-binaries/releases/download/15.1.0-rt_v12-rev0/x86_64-15.1.0-release-posix-seh-ucrt-rt_v12-rev0.7z
        7z x x86_64-release-posix-seh-ucrt.7z -oD:\a\QtBuild

    # 安装 Ninja
    - name: Setup Ninja
      run: |
        cd ..  #Directory: D:\a\QtBuild
        New-Item -ItemType Directory -Force -Path ninja
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip
        Expand-Archive -Path ninja.zip -DestinationPath ./ninja -Force

    # 安装 Emscripten SDK
    - name: Setup Emscripten
      run: |
        cd ..  #Directory: D:\a\QtBuild
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        .\emsdk.bat install ${{env.EMSCRIPTEN_VERSION}}
        .\emsdk.bat activate ${{env.EMSCRIPTEN_VERSION}}

    # 下载Host Qt
    - name: Download Host Qt
      run: |
        cd ..  #Directory: D:\a\QtBuild
        New-Item -ItemType Directory -Force -Path Qt/${{env.QT_VERSION}}-host
        cd Qt/${{env.QT_VERSION}}-host
        
        # 下载你提供的Host Qt
        curl -L -o host-qt.7z "https://github.com/yuanpeirong/buildQt/releases/download/Qt6.9.1_rev0/Qt_6.9.1-static-Release_mingw1510_64_UCRT.7z"
        7z x host-qt.7z

    # 创建目录结构
    - name: Create directories
      run: |
        cd ..  #Directory: D:\a\QtBuild
        New-Item -ItemType Directory -Force -Path Qt
        New-Item -ItemType Directory -Force -Path Qt/${{env.QT_VERSION}}
        New-Item -ItemType Directory -Force -Path Qt/${{env.QT_VERSION}}-static

    # 下载 Qt 源码
    - name: Download Qt Source
      run: |
        cd ../Qt  #Directory: D:\a\QtBuild\Qt
        echo "Downloading Qt source..."
        curl -L -o qt-everywhere-src-${{env.QT_VERSION}}.zip https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-src-${{env.QT_VERSION}}.zip
        
        echo "Download completed. File size:"
        Get-ChildItem qt-everywhere-src-${{env.QT_VERSION}}.zip | Select-Object Name, Length
        
        echo "Extracting Qt source..."
        7z x qt-everywhere-src-${{env.QT_VERSION}}.zip -o${{env.QT_VERSION}} -y
        
        echo "Extraction completed. Checking contents:"
        Get-ChildItem ${{env.QT_VERSION}} | Select-Object Name

    # 构建Qt
    - name: Build Qt
      timeout-minutes: 360  # 6小时超时
      shell: cmd
      run: |
        call "D:\a\QtBuild\QtBuild\Qt6Build\Build_Qt6.9.1_wasm32-emscripten3.1.70_gcc15.1.cmd"

    # 打包
    - name: Package binaries
      run: |
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-static -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z